name: telegram-file-bot
services:
  - name: bot
    type: web
    env: python
    build:
      commands:
        - pip install -r requirements.txt
    run:
      command: python bot.py
    env_vars:
      - key: API_ID
        value: "your_api_id"
      - key: API_HASH
        value: "your_api_hash"
      - key: BOT_TOKEN
        value: "your_bot_token"
